type Mutation {
    createSession(name: String): UserSession,
    appendThread(id: String, request: String): String
}

type Query {
    getSession(id: String): UserSession,
    getLog(id: String): [OpenAIMessage],
    getLatest(id: String): OpenAIMessage,
}

# Custom Types

type UserSession {
    id: ID!,
    name: String,
    openAIInit: Boolean,
    conversationLog: [OpenAIMessage!]!
}

type OpenAIMessage {
    role: String!,
    content: String!
}